name: task_hypergraph
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pip
  - python>=3.10
  - jupyter
  - scipy
  - optuna
  - numpy
  - scikit-learn
  - requests
  - matplotlib
  - pytorch 
  - torchvision 
  - torchaudio 
  - pytorch-cuda>=12.1
  - tqdm

